spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@forwork_high?TNS_ADMIN=C:/.repo/Wallet_forWORK
    username: ADMIN
    password: emptyCASTLE13
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081